# Generated by Django 5.2.3 on 2025-06-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_remove_master_salon_remove_master_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="master",
            name="service",
        ),
        migrations.AddField(
            model_name="master",
            name="services",
            field=models.ManyToManyField(
                to="bot.service", verbose_name="Услуги мастера"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="treatment",
            field=models.CharField(
                choices=[
                    ("Hair", "Стилист"),
                    ("Nail", "Ноготочки"),
                    ("Makeup", "Макияж"),
                ],
                max_length=10,
                verbose_name="Тип услуги",
            ),
        ),
    ]
