# Generated by Django 5.2.3 on 2025-06-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_remove_master_service_master_services_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masters",
                to="bot.salon",
                verbose_name="Салон",
            ),
        ),
    ]
