# Generated by Django 5.2.3 on 2025-06-25 11:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tg_id",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя клиента")),
                (
                    "phonenumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=12, region=None, verbose_name="Номер телефона"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="Адрес салона"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment",
                    models.CharField(max_length=100, verbose_name="Название процедуры"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=6, verbose_name="Цена"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя мастера")),
                ("salon", models.ManyToManyField(to="bot.salon", verbose_name="Салон")),
                (
                    "service",
                    models.ManyToManyField(to="bot.service", verbose_name="Услуга"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="Дата процедуры")),
                (
                    "slot",
                    models.CharField(
                        default="", max_length=13, verbose_name="Время записи"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправилось напоминание"
                    ),
                ),
                (
                    "registration_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Когда произведена бронь"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.master",
                        verbose_name="Мастер",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.salon",
                        verbose_name="Салон",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
        ),
    ]
