# Generated by Django 5.2.3 on 2025-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_alter_master_salon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="treatment",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Название услуги"
            ),
        ),
    ]
