# Generated by Django 5.2.3 on 2025-06-26 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_alter_service_treatment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="master",
            options={"verbose_name": "Мастер", "verbose_name_plural": "Мастера"},
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={"verbose_name": "Запись", "verbose_name_plural": "Записи"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
        migrations.AlterField(
            model_name="registration",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.master",
                verbose_name="Мастер",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.salon",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="slot",
            field=models.CharField(
                choices=[
                    ("09:00-10:00", "09:00-10:00"),
                    ("10:00-11:00", "10:00-11:00"),
                    ("11:00-12:00", "11:00-12:00"),
                    ("12:00-13:00", "12:00-13:00"),
                    ("13:00-14:00", "13:00-14:00"),
                    ("14:00-15:00", "14:00-15:00"),
                    ("15:00-16:00", "15:00-16:00"),
                ],
                max_length=13,
                verbose_name="Время записи",
            ),
        ),
    ]
