# Generated by Django 5.2.3 on 2025-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_alter_client_options_alter_master_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salon",
            options={"verbose_name": "Салон", "verbose_name_plural": "Салоны"},
        ),
        migrations.AlterField(
            model_name="registration",
            name="registration_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Когда произведена запись"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="slot",
            field=models.CharField(
                choices=[
                    ("09:00", "09:00"),
                    ("10:00", "10:00"),
                    ("11:00", "11:00"),
                    ("12:00", "12:00"),
                    ("13:00", "13:00"),
                    ("14:00", "14:00"),
                    ("15:00", "15:00"),
                    ("16:00", "16:00"),
                    ("17:00", "17:00"),
                ],
                max_length=13,
                verbose_name="Время записи",
            ),
        ),
    ]
