# Generated by Django 5.2.3 on 2025-06-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_masterschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='salon',
        ),
    ]
